all: false
dir: '{{.InterfaceDir}}/mocks'
filename: '{{.InterfaceName}}.go'
force-file-write: true
formatter: goimports
generate: true
log-level: info
structname: '{{.InterfaceName}}'
pkgname: mocks
recursive: false
template: testify
packages:
  github.com/viqueen/claude-go-playground/grpc-backend/pkg/search:
    interfaces:
      Search:
  github.com/viqueen/claude-go-playground/grpc-backend/pkg/embed:
    interfaces:
      Embedder:
  github.com/viqueen/claude-go-playground/grpc-backend/internal/outbox/space:
    interfaces:
      IndexStore:
