sonar.projectKey=viqueen_claude-go-playground
sonar.organization=viqueen-github

sonar.sources=grpc-backend,connect-rpc-backend
sonar.tests=.

sonar.go.coverage.reportPaths=grpc-backend/tmp/coverage.out