// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewEmbedder creates a new instance of Embedder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEmbedder(t interface {
	mock.TestingT
	Cleanup(func())
}) *Embedder {
	mock := &Embedder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Embedder is an autogenerated mock type for the Embedder type
type Embedder struct {
	mock.Mock
}

type Embedder_Expecter struct {
	mock *mock.Mock
}

func (_m *Embedder) EXPECT() *Embedder_Expecter {
	return &Embedder_Expecter{mock: &_m.Mock}
}

// Embed provides a mock function for the type Embedder
func (_mock *Embedder) Embed(ctx context.Context, text string) ([]float32, error) {
	ret := _mock.Called(ctx, text)

	if len(ret) == 0 {
		panic("no return value specified for Embed")
	}

	var r0 []float32
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]float32, error)); ok {
		return returnFunc(ctx, text)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []float32); ok {
		r0 = returnFunc(ctx, text)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]float32)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, text)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Embedder_Embed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Embed'
type Embedder_Embed_Call struct {
	*mock.Call
}

// Embed is a helper method to define mock.On call
//   - ctx context.Context
//   - text string
func (_e *Embedder_Expecter) Embed(ctx interface{}, text interface{}) *Embedder_Embed_Call {
	return &Embedder_Embed_Call{Call: _e.mock.On("Embed", ctx, text)}
}

func (_c *Embedder_Embed_Call) Run(run func(ctx context.Context, text string)) *Embedder_Embed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Embedder_Embed_Call) Return(float32s []float32, err error) *Embedder_Embed_Call {
	_c.Call.Return(float32s, err)
	return _c
}

func (_c *Embedder_Embed_Call) RunAndReturn(run func(ctx context.Context, text string) ([]float32, error)) *Embedder_Embed_Call {
	_c.Call.Return(run)
	return _c
}
