// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package space

import (
	"context"

	"github.com/gofrs/uuid/v5"
	mock "github.com/stretchr/testify/mock"
	"github.com/viqueen/claude-go-playground/grpc-backend/gen/db/collaboration"
)

// NewMockIndexStore creates a new instance of MockIndexStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIndexStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIndexStore {
	mock := &MockIndexStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIndexStore is an autogenerated mock type for the IndexStore type
type MockIndexStore struct {
	mock.Mock
}

type MockIndexStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIndexStore) EXPECT() *MockIndexStore_Expecter {
	return &MockIndexStore_Expecter{mock: &_m.Mock}
}

// GetSpace provides a mock function for the type MockIndexStore
func (_mock *MockIndexStore) GetSpace(ctx context.Context, id uuid.UUID) (collaboration.CollaborationSpace, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetSpace")
	}

	var r0 collaboration.CollaborationSpace
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (collaboration.CollaborationSpace, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) collaboration.CollaborationSpace); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(collaboration.CollaborationSpace)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIndexStore_GetSpace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSpace'
type MockIndexStore_GetSpace_Call struct {
	*mock.Call
}

// GetSpace is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockIndexStore_Expecter) GetSpace(ctx interface{}, id interface{}) *MockIndexStore_GetSpace_Call {
	return &MockIndexStore_GetSpace_Call{Call: _e.mock.On("GetSpace", ctx, id)}
}

func (_c *MockIndexStore_GetSpace_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockIndexStore_GetSpace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIndexStore_GetSpace_Call) Return(collaborationSpace collaboration.CollaborationSpace, err error) *MockIndexStore_GetSpace_Call {
	_c.Call.Return(collaborationSpace, err)
	return _c
}

func (_c *MockIndexStore_GetSpace_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (collaboration.CollaborationSpace, error)) *MockIndexStore_GetSpace_Call {
	_c.Call.Return(run)
	return _c
}
