// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/gofrs/uuid/v5"
	mock "github.com/stretchr/testify/mock"
	"github.com/viqueen/claude-go-playground/grpc-backend/pkg/search"
)

// NewSearch creates a new instance of Search. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSearch(t interface {
	mock.TestingT
	Cleanup(func())
}) *Search {
	mock := &Search{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Search is an autogenerated mock type for the Search type
type Search struct {
	mock.Mock
}

type Search_Expecter struct {
	mock *mock.Mock
}

func (_m *Search) EXPECT() *Search_Expecter {
	return &Search_Expecter{mock: &_m.Mock}
}

// CreateIndexIfNotExists provides a mock function for the type Search
func (_mock *Search) CreateIndexIfNotExists(ctx context.Context, index string, mapping []byte) error {
	ret := _mock.Called(ctx, index, mapping)

	if len(ret) == 0 {
		panic("no return value specified for CreateIndexIfNotExists")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []byte) error); ok {
		r0 = returnFunc(ctx, index, mapping)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Search_CreateIndexIfNotExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateIndexIfNotExists'
type Search_CreateIndexIfNotExists_Call struct {
	*mock.Call
}

// CreateIndexIfNotExists is a helper method to define mock.On call
//   - ctx context.Context
//   - index string
//   - mapping []byte
func (_e *Search_Expecter) CreateIndexIfNotExists(ctx interface{}, index interface{}, mapping interface{}) *Search_CreateIndexIfNotExists_Call {
	return &Search_CreateIndexIfNotExists_Call{Call: _e.mock.On("CreateIndexIfNotExists", ctx, index, mapping)}
}

func (_c *Search_CreateIndexIfNotExists_Call) Run(run func(ctx context.Context, index string, mapping []byte)) *Search_CreateIndexIfNotExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Search_CreateIndexIfNotExists_Call) Return(err error) *Search_CreateIndexIfNotExists_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Search_CreateIndexIfNotExists_Call) RunAndReturn(run func(ctx context.Context, index string, mapping []byte) error) *Search_CreateIndexIfNotExists_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type Search
func (_mock *Search) Delete(ctx context.Context, index string, id uuid.UUID) error {
	ret := _mock.Called(ctx, index, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, index, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Search_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type Search_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - index string
//   - id uuid.UUID
func (_e *Search_Expecter) Delete(ctx interface{}, index interface{}, id interface{}) *Search_Delete_Call {
	return &Search_Delete_Call{Call: _e.mock.On("Delete", ctx, index, id)}
}

func (_c *Search_Delete_Call) Run(run func(ctx context.Context, index string, id uuid.UUID)) *Search_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Search_Delete_Call) Return(err error) *Search_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Search_Delete_Call) RunAndReturn(run func(ctx context.Context, index string, id uuid.UUID) error) *Search_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Find provides a mock function for the type Search
func (_mock *Search) Find(ctx context.Context, index string, criteria search.Criteria) (*search.Page, error) {
	ret := _mock.Called(ctx, index, criteria)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 *search.Page
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, search.Criteria) (*search.Page, error)); ok {
		return returnFunc(ctx, index, criteria)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, search.Criteria) *search.Page); ok {
		r0 = returnFunc(ctx, index, criteria)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*search.Page)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, search.Criteria) error); ok {
		r1 = returnFunc(ctx, index, criteria)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Search_Find_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Find'
type Search_Find_Call struct {
	*mock.Call
}

// Find is a helper method to define mock.On call
//   - ctx context.Context
//   - index string
//   - criteria search.Criteria
func (_e *Search_Expecter) Find(ctx interface{}, index interface{}, criteria interface{}) *Search_Find_Call {
	return &Search_Find_Call{Call: _e.mock.On("Find", ctx, index, criteria)}
}

func (_c *Search_Find_Call) Run(run func(ctx context.Context, index string, criteria search.Criteria)) *Search_Find_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 search.Criteria
		if args[2] != nil {
			arg2 = args[2].(search.Criteria)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Search_Find_Call) Return(page *search.Page, err error) *Search_Find_Call {
	_c.Call.Return(page, err)
	return _c
}

func (_c *Search_Find_Call) RunAndReturn(run func(ctx context.Context, index string, criteria search.Criteria) (*search.Page, error)) *Search_Find_Call {
	_c.Call.Return(run)
	return _c
}

// Index provides a mock function for the type Search
func (_mock *Search) Index(ctx context.Context, index string, id uuid.UUID, document any) error {
	ret := _mock.Called(ctx, index, id, document)

	if len(ret) == 0 {
		panic("no return value specified for Index")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uuid.UUID, any) error); ok {
		r0 = returnFunc(ctx, index, id, document)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Search_Index_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Index'
type Search_Index_Call struct {
	*mock.Call
}

// Index is a helper method to define mock.On call
//   - ctx context.Context
//   - index string
//   - id uuid.UUID
//   - document any
func (_e *Search_Expecter) Index(ctx interface{}, index interface{}, id interface{}, document interface{}) *Search_Index_Call {
	return &Search_Index_Call{Call: _e.mock.On("Index", ctx, index, id, document)}
}

func (_c *Search_Index_Call) Run(run func(ctx context.Context, index string, id uuid.UUID, document any)) *Search_Index_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 any
		if args[3] != nil {
			arg3 = args[3].(any)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *Search_Index_Call) Return(err error) *Search_Index_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Search_Index_Call) RunAndReturn(run func(ctx context.Context, index string, id uuid.UUID, document any) error) *Search_Index_Call {
	_c.Call.Return(run)
	return _c
}
